Test endpoint api open library
wx-inc-trainings/me-rails pull request #4
Opened 2021-05-31 15:24 UTC by maxy96

# Summary
* Testing of endpoint '/api/open_library/:isbn'
   * With status code 200
       * Response body is not null and with content isbn, title, subtitle, authors, number_of_pages
   * With status code 404
       * Response body with message "book not found" 

# Trello Card
https://trello.com/c/6decFihF/38-3-implementar-fictium-y-crear-test-para-el-endpoint-de-book-information 

# Screenshot
![Captura de Pantalla 2021-05-31 a la(s) 12 09 10](https://user-images.githubusercontent.com/53832928/120213215-5450ae80-c209-11eb-917a-cb742c540009.png)

2021-05-31 15:26 UTC, maxy96 commented
for some reason my * .key files were uploaded

2021-05-31 17:40 UTC, blacksam07 requested changes

2021-05-31 17:40 UTC, blacksam07 commented on app/controllers/api/open_library_controller.rb
> +module Api
@maxy96 Change the base branch, you already included these changes into another PR # 3

2021-05-31 17:40 UTC, blacksam07 commented on spec/request/api_open_library_spec.rb
> +  describe 'when using ISBN:2' do
the `action`  statement after `describe` define and method that you use in the test

look this 
```ruby
describe PostsController do
  describe action 'GET #index' do # `action` after describe define the method that you make testing
    describe example 'without errors' do # `example` after describe define that is an example of the action
        default_example # You can select an example to be marked as default in your action

        before do
            get :index
        end

        # ... your tests
    end
  end
end

```
```suggestion
  describe action 'Get book info' do
```

2021-05-31 17:40 UTC, blacksam07 commented on spec/request/api_open_library_spec.rb
> +RSpec.describe 'Request to /api/open_library/:isbn', type: :request do
this describe is for the class that you make the testing, Controller or Service
```ruby
RSpec.describe OpenLibraryService do
```

```ruby
RSpec.describe Api::OpenLibraryController do
```

2021-05-31 17:40 UTC, blacksam07 commented on spec/request/api_open_library_spec.rb
> +    before { get '/api/open_library/2' }
you need to change, we testing controllers or services or both but not only a request, this way you testing a controller
```ruby
before
  get :show, params: { isbn: isbn }
end

describe example 'with valid value' do
  let(:isbn) { 2 }

  it 'status code 200' do 
    expect(response).to have_http_status(200)
  end

  ...
end
```

2021-06-01 20:49 UTC, blacksam07 approved these changes

2021-06-01 20:49 UTC, blacksam07 commented on spec/rails_helper.rb
> +  Fictium.configuration.postman.api_url = Rails.application.credentials.config[:base_uri]
you can drop this lines

2021-06-01 20:49 UTC, blacksam07 commented
@maxy96 fix the conflicts

2021-06-01 22:20 UTC, merged