Book controller
wx-inc-trainings/me-rails pull request #8
Opened 2021-06-10 14:16 UTC by maxy96

# Summary
* Created Book controller with routes of index and show
   * Panko Serializer installing 
       * Added to format the book info
   * Wor-paginate installing
       * Added to paginate books on index path
* Routes protected with authentication

# Trello Card
https://trello.com/c/PeTwCjuc/20-2-crear-rutas-index-y-show-para-book
https://trello.com/c/XvwVOyKd/33-1-paginar-los-endpoints-de-listados  

# Screenshot
![Captura de Pantalla 2021-06-10 a la(s) 11 13 31](https://user-images.githubusercontent.com/53832928/121540502-e7919d00-c9dc-11eb-92fc-e532109bbc8f.png)
![Captura de Pantalla 2021-06-10 a la(s) 11 15 26](https://user-images.githubusercontent.com/53832928/121540820-2c1d3880-c9dd-11eb-9cc8-d98042b72586.png)

2021-06-10 14:35 UTC, blacksam07 requested changes

2021-06-10 14:35 UTC, blacksam07 commented on app/assets/stylesheets/book.scss
> +// Place all the styles related to the Book controller here.
delete this file

2021-06-10 14:35 UTC, blacksam07 commented on app/controllers/api/book_controller.rb
> +    include Wor::Paginate
move this to ApplicationController

2021-06-10 14:35 UTC, blacksam07 commented on app/helpers/book_helper.rb
> +module BookHelper
Useless file

2021-06-10 14:35 UTC, blacksam07 commented on config/application.rb
> +    end
Move this config to wor-paginate initializer 


* Then you can run `rails generate wor:paginate:install` to create the initializer for configuration details, including default formatter class, page and limit params and default page number.

2021-06-10 16:02 UTC, blacksam07 approved these changes

2021-06-14 13:43 UTC, redwarewolf approved these changes
I'd add rubocop to fix some spacing errors you are having

2021-06-14 19:21 UTC, merged